[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
dotenv = "0.15.0"
env_logger = "0.11.5"
log = "0.4.22"
rustfft = "6.2.0"
serialport = "4.6.0"
ureq = "2.10.1"
